### ISSUE TITLE
reconsider defaults

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-encoding#38]
min word frequency and number of folds

**Comment by hvgazula** [comment]
Who is this assigned to?

**Comment by zkokaja** [comment]
We should discuss this in our next meeting

**Comment by zkokaja** [comment]
Should ask everyone running encoding what values they use to ensure everyone is aware and on the same page; then we can set defaults as is.

**Comment by VeritasJoker** [comment]
For 247, I use mwf = 0 and number of folds = 10. For podcast, I use mwf = 5 and number of folds = 10

**Comment by zkokaja** [comment]
Make these consistent for 24/7 defaults as comment above:
- https://github.com/hassonlab/247-encoding/blob/main/Makefile#L115-L119
- https://github.com/hassonlab/247-encoding/blob/main/scripts/tfsenc_parser.py#L38-L39
