### ISSUE TITLE
Remove hardcoded 50 and replace with args.pca_to

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-encoding#41]
https://github.com/hassonlab/247-encoding/blob/main/code/tfsenc_utils.py#L90

**Comment by VeritasJoker** [comment]
This should be done now with dev_branch.
For now, if args.pca_to == 0, it doesn't do pca, otherwise it does it based on the integer input.

In the future, could add also the variance (either to the same argument or a different one) (Leaving this issue open for this)

**Comment by zkokaja** [comment]
This is already merged
