### ISSUE TITLE
Remove redundant function

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-encoding#46]
https://github.com/hassonlab/247-encoding/blob/03e73d281600e34e8a584025f0895b0e2aa93d69/scripts/tfsenc_read_datum.py#L95

Maybe consider moving to 247-pickling (what exactly is this function/column needed for).

**Comment by hvgazula** [comment]
Is this function https://github.com/hassonlab/247-pickling/blob/2fa1ef112ec80af92b5d78b2903daee130fb20ec/scripts/tfspkl_main.py#L30 a duplicate?

**Comment by zkokaja** [comment]
And remove https://github.com/hassonlab/247-encoding/blob/03e73d281600e34e8a584025f0895b0e2aa93d69/scripts/tfsenc_read_datum.py#L165

**Comment by zkokaja** [comment]
Remove function and call because `conv_signal_length` is not being used in encoding. But double check @hvgazula

**Comment by zkokaja** [comment]
Also look into whether we need the add_conv_onset/offset functions

**Comment by VeritasJoker** [comment]
Double-checked and deleted `add_signal_length`
For `add_convo_onset_and_offset`, not sure if the columns are in pickling yet. Need to test with newest pickles

**Comment by zkokaja** [comment]
@hvgazula check pickling side for these columns

**Comment by VeritasJoker** [comment]
Resolved
