### ISSUE TITLE
Replace code snippet to exclude nonwords

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-encoding#47]
https://github.com/hassonlab/247-encoding/blob/03e73d281600e34e8a584025f0895b0e2aa93d69/scripts/tfsenc_read_datum.py#L228-L230

Replace with

https://github.com/hassonlab/247-pickling/blob/main/scripts/tfspkl_utils.py#L141

**Comment by zkokaja** [comment]
Non words should and are defined in pickling, not in encoding

**Comment by zkokaja** [comment]
Use the non_word column from the base dataframe, as defined in https://github.com/hassonlab/247-pickling/blob/main/scripts/tfspkl_utils.py#L141
