### ISSUE TITLE
Processing subject with significant electrode list

### ISSUE THREAD

**Issue by VeritasJoker** [hassonlab/247-encoding#51]
Potentially another bug caused by pickle hierarchy: the new 777_electrode_name.pkl loads the subject column as 'object' and not 'int' so when merging with significant electrode list [here](https://github.com/hassonlab/247-encoding/blob/03e73d281600e34e8a584025f0895b0e2aa93d69/scripts/tfsenc_main.py#L56) causes issues.

Should be fixed by adding this `df["subject"] = df.subject.astype(int)`
but not sure so putting it here

@leoniekerken is testing it out currently.

**Comment by hvgazula** [comment]
I am not testing for Bobbi's all_electrodes.csv format. Instead, please use all_electrodes2.csv.

**Comment by leoniekerken** [comment]
The problem was caused because of a workaround that I incorrectly used for the copy-embedding command. After copying the files the correct way (only the embeddings), it worked.

**Comment by VeritasJoker** [comment]
Ok then it should be solved by just adding this line `df["subject"] = df.subject.astype(int)` before [this](https://github.com/hassonlab/247-encoding/blob/03e73d281600e34e8a584025f0895b0e2aa93d69/scripts/tfsenc_main.py#L56)

Let's just update it to main for the next codebase meeting

Also the significant electrode list for podcast should be "160-phase-5000-sig-elec-glove50d-perElec-FDR-01-LH_newVer.csv". There are also newer versions named "podcast_160.csv". They should all be the same file with 160 sig electrodes.

**Comment by VeritasJoker** [comment]
Oh ok. @leoniekerken Can you test encoding without this line `df["subject"] = df.subject.astype(int)` and see if it still works?
If it does work then we close this issue. If not we will add this line for the next codebase meeting. Thanks!

**Comment by leoniekerken** [comment]
Yes, it works without this line. Thanks for your help!
