### ISSUE TITLE
Redundant import

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-encoding#55]
https://github.com/hassonlab/247-encoding/blob/a45025b5b07bdc25caa02e4a77ec15e114ba195f/scripts/tfsenc_read_datum.py#L3

This is not being used anywhere. @VeritasJoker, please confirm.

**Comment by hvgazula** [comment]
Same https://github.com/hassonlab/247-encoding/blob/main/scripts/tfsenc_main.py#L9

**Comment by VeritasJoker** [comment]
I think its from the older functions. Yeah we can delete them
