### ISSUE TITLE
Read data from pickle

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-encoding#6]
I expected this project to read signal data from the pickle, but it looks like it's getting it from the conversations folder:

https://github.com/hassonlab/247-encoding/blob/ad13bd0e2b0a00517d7c5edced555557f97d627c/code/tfsenc_main.py#L97

I suppose this is faster than loading the entire 12GB, was that the reason for implementing it this way?

**Comment by hvgazula** [comment]
> I expected this project to read signal data from the pickle, but it looks like it's getting it from the conversations folder:
> 
> https://github.com/hassonlab/247-encoding/blob/ad13bd0e2b0a00517d7c5edced555557f97d627c/code/tfsenc_main.py#L97
> 
> I suppose this is faster than loading the entire 12GB, was that the reason for implementing it this way?

Yes.

**Comment by zkokaja** [comment]
If we save the signal file as a numpy archive, do you know if it's possible to just read one electrode at a time without reading the full thing?

**Comment by hvgazula** [comment]
Need to check this https://msgpack.org/
