### ISSUE TITLE
Problems with multiprocessing

### ISSUE THREAD

**Issue by VeritasJoker** [hassonlab/247-encoding#71]
It seems like this line is causing some problems when submitting jobs to slurm. Forgot to include the error before deleting all the logs. Will try to reproduce again

https://github.com/hassonlab/247-encoding/blob/82042c0467e78dac671e070c0bc069b44894215c/scripts/tfsenc_main.py#L199

**Comment by hvgazula** [comment]
Please also paste the submit.sh script along with the log file. Thanks.

*Thanks & Regards,*
*Harsha Gazula*

**Comment by VeritasJoker** [comment]
I tried but couldn't replicate the same error message. For now, I just replace this with `p = Pool(4)` and it works fine.

**Comment by hvgazula** [comment]
I think I now know what this issue is. I found out by doing my own work :). `cpu_count()` returns the "total number of cpus on the node" and not the number of "cpus requested".

**Comment by hvgazula** [comment]
Replacing `cpu_count()` with `len(os.sched_getaffinity(0))` should do.

**Comment by VeritasJoker** [comment]
> I think I now know what this issue is. I found out by doing my own work :). `cpu_count()` returns the "total number of cpus on the node" and not the number of "cpus requested".

lol that's what I suspected but never confirmed it. No matter how many memory I require for a job it always runs out : )

**Comment by hvgazula** [comment]
@VeritasJoker Did you test this change?

**Comment by VeritasJoker** [comment]
> @VeritasJoker Did you test this change?

I trust you : )

**Comment by hvgazula** [comment]
> > @VeritasJoker Did you test this change?
> 
> I trust you : )

the number and type of issues we have had so far should tell you that you shouldn't;t 😛
