### ISSUE TITLE
filter out nans in onset/offset

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-encoding#72]
similar to how we do for embeddings `    df["is_nan"] = df["embeddings"].apply(lambda x: np.isnan(x).all())`

**Comment by VeritasJoker** [comment]
Does this suffice: https://github.com/hassonlab/247-encoding/blob/e0b7468824bc950f15dd8e47f9b7c4bdb3615109/scripts/tfsenc_read_datum.py#L117

or we need one for the onset/offset as well?

**Comment by hvgazula** [comment]
no harm in dropping them as well just in case.
