### ISSUE TITLE
print standard error on the correlation from all folds

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-encoding#74]
https://github.com/hassonlab/247-encoding/blob/e0b7468824bc950f15dd8e47f9b7c4bdb3615109/scripts/tfsenc_utils.py#L175-L185

Write a `for` loop around `rp`  (make it a `dict` or `list`) using `fold_tes` as indexing. For example

```
rp = dict()
for i in fold_tes.unique():
    rp[i], _, _ = encColCorr(Y_new[fold_tes == i], PY_hat[fold_tes == i]) 
```

**Comment by hvgazula** [comment]
@VeritasJoker comments?

**Comment by VeritasJoker** [comment]
Yeah should work

**Comment by leoniekerken** [comment]
Thanks! I'm on it.
